"""adding new col

Revision ID: 5d9764d90232
Revises: dc805fbe1d26
Create Date: 2025-09-07 20:34:19.059824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9764d90232'
down_revision: Union[str, Sequence[str], None] = 'dc805fbe1d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('new_dummy_col', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'new_dummy_col')
    # ### end Alembic commands ###
